version: '3.8'

services:
  # 🖥️ Servicio de desarrollo
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/heroes
    networks:
      - heroes-network
    depends_on:
      - mongodb

  # 🚀 Servicio de producción
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/heroes
    networks:
      - heroes-network
    depends_on:
      - mongodb
    profiles:
      - prod

  # 🗃️ Servicio de base de datos MongoDB
  mongodb:
    image: mongo:8.0
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=heroes
    networks:
      - heroes-network

# 📁 Definición de volúmenes
volumes:
  node_modules:
  mongodb-data:

# 🌐 Definición de redes
networks:
  heroes-network:
    driver: bridge